baseURL: "/"
languageCode: "en-us"
title: "Phil Ranzato"
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2
    
params:
  customCSS: false

  favicon: "/images/favicon.webp"
  description: "Phil Ranzato portfolio website."

  # home
  disable_home: false
  profile_image: "/images/profile.webp"
  name: "Phil Ranzato"
  namecolor: ffc107
  profession: "Cloud Native & DevOps Engineer"
  github: "https://github.com/PhilRanzato"
  linkedin: "https://linkedin.com/phil-ranzato"
  medium: "https://medium.com/@philranzato"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Phil Ranzato, a DevOps Engineer. I always tend to learn new modern technologies, even outside my field."
  descripe_l2_person: "You can find my works [here](#projects)"
  skills:
    - name: Kubernetes
      percentage: 97
    - name: Ansible
      percentage: 95
    - name: Terraform
      percentage: 90
    - name: AWS/GCP/Azure
      percentage: 80
    - name: Python
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Kiratech Swiss SA"
      role: "Cloud Native & DevOps Engineer"
      startdate: Oct 2019
      enddate: present
      featuredpoints:
        - point: Infrastructure as Code Expert.
        - point: Kubernetes Certified Administrator.
        - point: Elastic Stack Expert.
        - point: Guiding companies into the Digital transformation.

  # Education
  disable_education: false
  education:
    - degree: "BSc"
      branch: "Computer Science and Engineering"
      university: "Politecnico di Milano"
      startedyear: "2014"
      graduation: "2017"
    - degree: "MSc"
      branch: "Computer Science and Machine Learning"
      university: "Politecnico di Milano"
      startedyear: "2017"
      graduation: "2019"

  # Projects
  disable_projects: false

  # Achievements
  disable_achievements: false
  achievements:
    - title: CKA
      description: I took the Certified Kubernetes Administrator certification with a score of 97/100 on August 15, 2020.
      img: /images/achievements/cka.webp
      url: https://www.credly.com/badges/59e37847-6e12-4b2a-8347-38a13b06b5f7/public_url

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "philranzato@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
